// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.28;

// GENERATED from scripts/grove_univ4_pool_registry.json.
// Run `python3 scripts/generate_grove_pool_config.py` after intentionally changing
// oracle_pool_ids, and `python3 scripts/generate_grove_pool_config.py --check`
// before deploying. Do not edit this file manually.
library GroveUniV4PoolConfig {
    function initialPools() internal pure returns (bytes32[] memory pools) {
        pools = new bytes32[](10);
        pools[0] = 0xde47849dd91a1d9b90a775776ae012cfc6eb2eb2ce0fe7c5be770038dd71ae4e;
        pools[1] = 0x139e22b401c6df9596ee06815598b459f4d0777eb2e80961e5f87ed5a9beb298;
        pools[2] = 0x0d40eef4d9600a37016f34d089705e83d8d9e40ac80838abb04a278fa049e874;
        pools[3] = 0x799770994a3fc792ea684736316bebd2e2b9074a565c8a7ef64d45b2732e5618;
        pools[4] = 0x01d7d2d4d500c84be381c7c90466a803f1c0713179e00ad0e4ed8683da39e513;
        pools[5] = 0x2a2dfbb417f70fa3bfd09296f313b33a197fcba986d0b41705218d91b9544b14;
        pools[6] = 0xaa0b1a90c6188f42c3603998536418f4eeedccf20b999377dab7e4c6aafc5286;
        pools[7] = 0x2897b6ccd757711791a90b723df4f89567568859d040ff97d25cc4a5cb93ea03;
        pools[8] = 0x9fe7fb249f5fdacc3c102cb8f9c5e5b59b70da2ea96377804bcb58328b93441f;
        pools[9] = 0x20d117a32203158c46d0dce34ade2b2cbf846d151e9cea406e0463fe361d82ce;
    }
}
