name: test

on:
  push:
    branches:
    - master
    - develop
    - grove
    - merge-grove
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        suite: [spark, grove, coexistence]

    name: Foundry ${{ matrix.suite }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.5.1

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
        run: make test-${{ matrix.suite }}
        id: test

  maintenance:
    name: Grove maintenance scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: make test-python check-pools
